backbone: yolov8
cfg_path: third_party/yolov8/ultralytics/cfg/models/v8/yolov8n.yaml
nc: 80
use_fisheye_stem: false
replace_convs: true
fisheye:
  liftsamples: 4
  mc_samples: 32
  fill: 0.25
  knn: true
